version: '3'

services:
  app:
    build:
      context: ./django
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
  db:
    image: mysql:8
    ports:
      - "3306:3306"
    environment:
      - MYSQL_PASS=root
      