# Generated by Django 4.2 on 2023-05-17 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Telegram',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('api_key', models.CharField(default='', max_length=256)),
                ('group_name', models.CharField(default='', max_length=128)),
                ('message_id', models.CharField(default='', max_length=64)),
            ],
        ),
    ]
